language: node_js
node_js:
  - "8"

install:
  - npm install
  - npx lerna bootstrap

jobs:
  include:
      - name: "Unit Tests"
        script: npm test
      - name: "Lint"
        script: npm run lint
      - name: "Docs"
        script: npm run doc
      - name: "Benchmark Test"
        script: npm run benchmark
      - name: "Audit"
        script: npm audit

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
  provider: script
  script: "npm run release:publish"
  skip_cleanup: true
  on:
    node: "8"
    tags: true
