baseurl: "/"
exclude: ["_partials"]
permalink: /api/:categories/:title:output_ext
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "api"
      menuUrl: "api"
